services:
  gitlab:
    image: gitlab/gitlab-ce:17.5.3-ce.0
    container_name: gitlab
    hostname: gitlab
    restart: unless-stopped
    shm_size: "256m"
    ports:
      - "8929:8929"
      - "2224:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - gitlab_net

  gitlab_runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - gitlab_runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab_net

networks:
  gitlab_net: {}

volumes:
  gitlab_config: {}
  gitlab_logs: {}
  gitlab_data: {}
  gitlab_runner_config: {}